### ISSUE TITLE
[SciPy]: Test compiled packages at CI

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran-conda-testing#21]
We need to make a release covering PR: https://github.com/lfortran/lfortran/pull/2741

cc @certik @Shaikh-Ubaid

**Comment by certik** [comment]
Sure, I just made a new release: https://github.com/lfortran/lfortran/releases/tag/v0.29.0

**Comment by Shaikh-Ubaid** [comment]
I think this has to be now updated in conda and then tested here in this respository.
